doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        # server_version: '8.0'  # Décommente si nécessaire
        dbname_suffix: ''
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        controller_resolver:
            auto_mapping: false
        dql:
            string_functions:
                JSON_EXTRACT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
        orm:
            auto_generate_proxy_classes: true
            validate_xml_mapping: false  # Désactivé pour éviter les erreurs inutiles en test

when@prod:
    doctrine:
        dbal:
            # Amélioration des performances en production
            options:
                1002: "SET SESSION sql_mode=(SELECT REPLACE(@@sql_mode, 'ONLY_FULL_GROUP_BY', ''))"
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            entity_managers:
                default:
                    mappings:
                        default:
                            type: attribute
                            dir: '%kernel.project_dir%/src/Entity'
                            prefix: 'App\Entity'
                            is_bundle: false
                            