name: Déploiement production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Déploiement sur VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
          
            cd /var/www/projet-gite/app
            git pull origin main

            npm install
            npm run build

            docker compose build php 
            docker compose up -d php 

            docker compose exec -T php php bin/console cache:clear --env=prod
            docker compose exec -T php php bin/console cache:warmup --env=prod

            docker compose exec -T --user=root php chown -R www-data:www-data /var/www/var
            docker compose exec -T --user=root php chmod -R 775 /var/www/var
