name: Déploiement production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Déploiement sur VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
          
            cd /var/www/projet-gite/app

            # S'assurer que l'utilisateur SSH a bien les droits
            sudo chown -R ubuntu:ubuntu .

            # Nettoyage pour éviter les conflits si des fichiers sont modifiés localement
            git reset --hard
            git clean -fd
            git pull origin main

            # Installation des dépendances
            npm install
            npm run build

            # Build et redémarrage du conteneur PHP
            docker compose build php 
            docker compose up -d php 

            # Clear + Warmup du cache Symfony en prod
            docker compose exec -T php php bin/console cache:clear --env=prod
            docker compose exec -T php php bin/console cache:warmup --env=prod

            # Permissions (important pour que Symfony fonctionne bien)
            docker compose exec -T --user=root php chown -R www-data:www-data /var/www/var
            docker compose exec -T --user=root php chmod -R 775 /var/www/var
